version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - code-server
    env_file:
      - .env
    environment:
      WEBSOCKET: "true"
      DOMAINS: "user:${CODER_BASICAUTH_PASSWORD:?Please set CODER_BASICAUTH_PASSWORD}@${CODER_HOST:?Please set CODER_HOST} -> http://code-server:8443"
      # STAGE: 'production'  # Don't enable this until you test everything works
    restart: always

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=${CODER_PASSWORD:?Please set CODER_PASSWORD}
      - SUDO_PASSWORD=${CODER_PASSWORD:?Please set CODER_PASSWORD}
    volumes:
      - ${CODER_CONFIG_DIR:?Please set CODER_CONFIG_DIR}:/config/.config/code-server
      - ${HEARTBEATS_FOLDER:?Please set HEARTBEATS_FOLDER}:/config/.local/share/code-server
    restart: unless-stopped

  heartbeats-watcher:
    build: ./heartbeats_watcher
    container_name: heartbeats_watcher
    env_file:
      - .env
    command: -t "${HEARTBEATS_TIMEOUT:?Please set HEARTBEATS_TIMEOUT}" -a "${HEARTBEATS_ACTION:?Please set HEARTBEATS_ACTION}" /app/heartbeats/heartbeat /app/heartbeats/sshbash_heartbeat
    volumes:
      - ${HEARTBEATS_FOLDER:?Please set HEARTBEATS_FOLDER}:/app/heartbeats
    restart: unless-stopped

  sshbash-heartbeat:
    build: ./heartbeats/sshbash
    container_name: sshbash_heartbeat
    env_file:
      - .env
    command: sshbash_heartbeat
    volumes:
      - ${HEARTBEATS_FOLDER:?Please set HEARTBEATS_FOLDER}:/app/heartbeats
    pid: "host"
    restart: unless-stopped
