version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - oauth2-proxy
    env_file:
      - .env
    environment:
      WEBSOCKET: "true"
      DOMAINS: "${CODER_HOST:?Please set CODER_HOST} -> http://oauth2-proxy:8080"
      STAGE: 'production'  # Don't set to 'production' this until you test everything works
    restart: always

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy
    links:
      - code-server
    env_file:
      - .env
    environment:
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:8080
      OAUTH2_PROXY_PROVIDER: github
      OAUTH2_PROXY_AUTHENTICATED_EMAILS_FILE: /config/emails
      OAUTH2_PROXY_UPSTREAMS: http://code-server:8443/
    volumes:
      - ${ALLOWED_EMAILS_LIST:?Please set ALLOWED_EMAILS_LIST}:/config/emails
    restart: always

  code-server:
    image: linuxserver/code-server
    container_name: code-server
    env_file:
      - .env
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD=${CODER_PASSWORD:?Please set CODER_PASSWORD}
      - SUDO_PASSWORD=${CODER_PASSWORD:?Please set CODER_PASSWORD}
      - ALLOWHTTP=true
      - ALLOW-HTTP=true
    volumes:
      - ${CODER_CONFIG_DIR:?Please set CODER_CONFIG_DIR}:/config/.config/code-server
      - ${HEARTBEATS_FOLDER:?Please set HEARTBEATS_FOLDER}:/config/.local/share/code-server
    restart: unless-stopped

  heartbeats-watcher:
    build: ./heartbeats_watcher
    container_name: heartbeats_watcher
    env_file:
      - .env
    command: -t "${HEARTBEATS_TIMEOUT:?Please set HEARTBEATS_TIMEOUT}" -a "${HEARTBEATS_ACTION:?Please set HEARTBEATS_ACTION}" -e "${HEARTBEATS_ACTION:?Please set HEARTBEATS_ACTION}" /app/heartbeats/heartbeat /app/heartbeats/sshbash_heartbeat
    volumes:
      - ${HEARTBEATS_FOLDER:?Please set HEARTBEATS_FOLDER}:/app/heartbeats
    restart: unless-stopped

  sshbash-heartbeat:
    build: ./heartbeats/sshbash
    container_name: sshbash_heartbeat
    env_file:
      - .env
    command: /app/heartbeats/sshbash_heartbeat
    volumes:
      - ${HEARTBEATS_FOLDER:?Please set HEARTBEATS_FOLDER}:/app/heartbeats
    pid: "host"
    restart: unless-stopped
